version: '3.1'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: scheduled_tips
    ports:
    - 127.0.0.1:5432:5432
  ngrok:
    image: wernight/ngrok
    restart: always
    environment:
      NGROK_PORT: 8080
    ports:
    - 127.0.0.1:4040:4040